[0m20:01:02.173877 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016035C8B620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000160381E7380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000160381E5E80>]}


============================== 20:01:02.177885 | 0c276601-d7b2-413e-90a7-c5cc1647d58e ==============================
[0m20:01:02.177885 [info ] [MainThread]: Running with dbt=1.9.6
[0m20:01:02.178883 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\edson\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt test', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:01:02.178883 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\edson\OneDrive\Maua_Pos_Graduacao\Modulo_III\Engenharia_de_dados\trabalho\projeto_dbt_2\engenharia-dados-2025-1\dbt_compose\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:01:02.180884 [debug] [MainThread]: Command `dbt test` failed at 20:01:02.180884 after 0.27 seconds
[0m20:01:02.180884 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001603858A000>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000160328B51C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000160328B5040>]}
[0m20:01:02.181896 [debug] [MainThread]: Flushing usage events
[0m20:01:02.820714 [debug] [MainThread]: An error was encountered while trying to flush usage events
