[0m19:57:22.438692 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002166DD2B590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002166DC2FD40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000216701F7B90>]}


============================== 19:57:22.449642 | 7a68e0ee-e52c-401b-86b6-b704046efbb7 ==============================
[0m19:57:22.449642 [info ] [MainThread]: Running with dbt=1.9.6
[0m19:57:22.450642 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\edson\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt test', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:57:22.451642 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\edson\OneDrive\Maua_Pos_Graduacao\Modulo_III\Engenharia_de_dados\trabalho\projeto_dbt_2\engenharia-dados-2025-1\dbt_compose\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:57:22.452643 [debug] [MainThread]: Command `dbt test` failed at 19:57:22.452643 after 0.26 seconds
[0m19:57:22.453641 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002167098AE70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021670D3BD40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002166DD2B590>]}
[0m19:57:22.453641 [debug] [MainThread]: Flushing usage events
[0m19:57:23.156685 [debug] [MainThread]: An error was encountered while trying to flush usage events
